config/routes.rb
Nambstore::Application.routes.draw do
 
 resources :store
 resources :line_items
  resources :carts

  get "store/index"
 

  resources :products
 
 match "/store/:id" => "store#show", :as=>'show'

  root :to => 'store#index', :as=>'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items, :dependent=> :destroy
  
  def add_product(product_id)
  current_item = line_items.where(:product_id => product_id).first
  if current_item
    current_item.quantity += 1
  else
    current_item = line_items.build(:product_id => product_id)
  end
   current_item
  end
  
  def total_price
line_items.to_a.sum { |item| item.total_price }
end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
        @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
       logger.error "Attempt to access invalid cart #{params[:id]}"
       redirect_to store_url, :notice => 'Invalid cart'
      else
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    #@cart = Cart.find(params[:id])
    @cart = current_cart
    @cart.destroy
    session[:cart_id]=nil
    respond_to do |format|
      format.html { redirect_to(store_url,:notice => 'Your cart is currently empty' ) }

      format.json { head :ok }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="style2 style10" >SHOPPING CART </div>
<div >
<table width="90%" border="0">
  <tr style="border-bottom:solid 1px #CCCCCC;">
    <td width="22%" class="style5">Item</td>
    <td width="33%">&nbsp;</td>
    <td width="8%"><span class="style5">Price</span></td>
    <td width="6%" class="style5">Qty</td>
    <td width="8%" class="style5">Total</td>
    <td width="23%"><div class="style5"></div></td>
  </tr>
<% @cart.line_items.each do |item| %>
  <tr>
    <td><%= image_tag(item.product.image_url,:size=>"102x74") %></td>
    <td class="style8"><%= item.product.title %></td>
    <td class="style7"><%= item.product.price %></td>
    <td class="style7"><%= item.quantity %></td>
    <td class="style7"><%= item.product.price %></td>
    <td><div class="style5"><a href="#" class="style8">remove</a></div></td>
  </tr>
  <% end %>
  <tr>
    <td><%= image_tag("namb/continue.png") %></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td class="style9">Subtotal: <%= number_to_currency(@cart.total_price) %></td>
  </tr>
  <tr>
       
  </tr>
  <tr>
    <td>
    	<%= link_to image_tag("namb/empty.png"),@cart, :metho => :delete, :confirm => 'Are You Sure ?' %>
    	
</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
	
    
	
	<td><%= image_tag("namb/checkout.png") %></td>
	
	</tr>
</table>

</div>


<div style="clear:both;"></div>



<div>
      <div align="right">
        <table width="215" border="0">
          <tr>
            <td width="74%"><%= link_to image_tag("namb/back2.png"), carts_path %></td>
            <td width="26%"><a href="index.html"><img src="images/namb/startover2.png" alt="" width="167" height="44" /></a></td>
          </tr>
        </table>
        </div>
	     
  </div>