config/routes.rb
Nambstore::Application.routes.draw do
 
 resources :store
 resources :line_items
  resources :carts

  get "store/index"
 

  resources :products
 
 match "/store/:id" => "store#show", :as=>'show'

  root :to => 'store#index', :as=>'store'

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products=Product.all
  end
  
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/index.html.erb
<p id="notice"><%= notice %></p>
<div class="style2" >PROMOTIONAL ITEMS</div>
<% @products.each do |product| %>
<a href="store/<%= product.id %>">
<div class="product">
	<div class="product1">
	  <div align="center"><%= image_tag(product.image_url,:size=>"102x74") %>
	</div>
</div>
<div class="product2 style3" align="center">
	<%= product.title %><br />
	<%= sprintf("$%0.02f", product.price) %><br/>	
</div>
</a>
</div>

<% end %>

app/views/store/show.html.erb
<p id="notice"><%= notice %></p>

<div class="middle">
    <div class="promotional">
      <div class="style2 style4" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SEND NORTH AMERICA NOTEPADS</div>
      <div class="product" style="margin-top:10px;"><%= image_tag(@product.image_url) %></div>
      <div style="float:right; margin-right:100px;">
        <table width="215" border="0">
          <tr>
            <td><div align="center" class="style5">Price</div></td>
          </tr>
          <tr>
            <td><div align="center" class="style6"><%= sprintf("$%0.02f", @product.price) %></div></td>
          </tr>
          <tr>
            <td><div align="center"></div></td>
          </tr>
          <tr>
            <td><form method="post" action="">
              <div align="center">
                <input name="text" type="text" style=" border:solid 1px #CCCCCC; width:50px; height:20px;" value="1" />
              </div>
            </form></td>
          </tr>
          <tr>
            <td><div align="center"></div></td>
          </tr>
          <tr>
            <td><div align="center">
            	<%= link_to image_tag("namb/add.png"), line_items_path(:product_id => @product.id) %>
            	
            	</div></td>
          </tr>
        </table>
      </div>
	  
    </div>
	<div style="clear:both;"></div>
    <div style="margin-top:30px;">
      <div align="right">
        <table width="215" border="0">
          <tr>
            <td width="66%"><%= link_to image_tag("namb/back2.png"), store_path %></td>
            <td width="34%"><%= image_tag("namb/startover2.png") %></a></td>
          </tr>
        </table>
        </div>